go.property("buffer1", resource.buffer("/game_objects/asteroids/buffers/empty1.buffer")) 
go.property("buffer2", resource.buffer("/game_objects/asteroids/buffers/empty2.buffer")) 
go.property("buffer3", resource.buffer("/game_objects/asteroids/buffers/empty3.buffer")) 
go.property("buffer4", resource.buffer("/game_objects/asteroids/buffers/empty4.buffer")) 
go.property("buffer5", resource.buffer("/game_objects/asteroids/buffers/empty5.buffer")) 
go.property("buffer6", resource.buffer("/game_objects/asteroids/buffers/empty6.buffer")) 
go.property("buffer7", resource.buffer("/game_objects/asteroids/buffers/empty7.buffer")) 
go.property("buffer8", resource.buffer("/game_objects/asteroids/buffers/empty8.buffer")) 
go.property("buffer9", resource.buffer("/game_objects/asteroids/buffers/empty9.buffer")) 
go.property("buffer10", resource.buffer("/game_objects/asteroids/buffers/empty10.buffer")) 
go.property("buffer11", resource.buffer("/game_objects/asteroids/buffers/empty11.buffer")) 
go.property("buffer12", resource.buffer("/game_objects/asteroids/buffers/empty12.buffer")) 
go.property("buffer13", resource.buffer("/game_objects/asteroids/buffers/empty13.buffer")) 
go.property("buffer14", resource.buffer("/game_objects/asteroids/buffers/empty14.buffer")) 
go.property("buffer15", resource.buffer("/game_objects/asteroids/buffers/empty15.buffer")) 
go.property("buffer16", resource.buffer("/game_objects/asteroids/buffers/empty16.buffer")) 
go.property("buffer17", resource.buffer("/game_objects/asteroids/buffers/empty17.buffer")) 
go.property("buffer18", resource.buffer("/game_objects/asteroids/buffers/empty18.buffer")) 
go.property("buffer19", resource.buffer("/game_objects/asteroids/buffers/empty19.buffer")) 
go.property("buffer20", resource.buffer("/game_objects/asteroids/buffers/empty20.buffer")) 
go.property("buffer21", resource.buffer("/game_objects/asteroids/buffers/empty21.buffer")) 
go.property("buffer22", resource.buffer("/game_objects/asteroids/buffers/empty22.buffer")) 
go.property("buffer23", resource.buffer("/game_objects/asteroids/buffers/empty23.buffer")) 
go.property("buffer24", resource.buffer("/game_objects/asteroids/buffers/empty24.buffer")) 
go.property("buffer25", resource.buffer("/game_objects/asteroids/buffers/empty25.buffer")) 
go.property("buffer26", resource.buffer("/game_objects/asteroids/buffers/empty26.buffer")) 
go.property("buffer27", resource.buffer("/game_objects/asteroids/buffers/empty27.buffer")) 
go.property("buffer28", resource.buffer("/game_objects/asteroids/buffers/empty28.buffer")) 
go.property("buffer29", resource.buffer("/game_objects/asteroids/buffers/empty29.buffer")) 
go.property("buffer30", resource.buffer("/game_objects/asteroids/buffers/empty30.buffer")) 
go.property("buffer31", resource.buffer("/game_objects/asteroids/buffers/empty31.buffer")) 
go.property("buffer32", resource.buffer("/game_objects/asteroids/buffers/empty32.buffer")) 
go.property("buffer33", resource.buffer("/game_objects/asteroids/buffers/empty33.buffer")) 
go.property("buffer34", resource.buffer("/game_objects/asteroids/buffers/empty34.buffer")) 
go.property("buffer35", resource.buffer("/game_objects/asteroids/buffers/empty35.buffer")) 
go.property("buffer36", resource.buffer("/game_objects/asteroids/buffers/empty36.buffer")) 
go.property("buffer37", resource.buffer("/game_objects/asteroids/buffers/empty37.buffer")) 
go.property("buffer38", resource.buffer("/game_objects/asteroids/buffers/empty38.buffer")) 
go.property("buffer39", resource.buffer("/game_objects/asteroids/buffers/empty39.buffer")) 
go.property("buffer40", resource.buffer("/game_objects/asteroids/buffers/empty40.buffer")) 
go.property("buffer41", resource.buffer("/game_objects/asteroids/buffers/empty41.buffer")) 
go.property("buffer42", resource.buffer("/game_objects/asteroids/buffers/empty42.buffer")) 
go.property("buffer43", resource.buffer("/game_objects/asteroids/buffers/empty43.buffer")) 
go.property("buffer44", resource.buffer("/game_objects/asteroids/buffers/empty44.buffer")) 
go.property("buffer45", resource.buffer("/game_objects/asteroids/buffers/empty45.buffer")) 
go.property("buffer46", resource.buffer("/game_objects/asteroids/buffers/empty46.buffer")) 
go.property("buffer47", resource.buffer("/game_objects/asteroids/buffers/empty47.buffer")) 
go.property("buffer48", resource.buffer("/game_objects/asteroids/buffers/empty48.buffer")) 
go.property("buffer49", resource.buffer("/game_objects/asteroids/buffers/empty49.buffer")) 
go.property("buffer50", resource.buffer("/game_objects/asteroids/buffers/empty50.buffer")) 
go.property("buffer51", resource.buffer("/game_objects/asteroids/buffers/empty51.buffer")) 
go.property("buffer52", resource.buffer("/game_objects/asteroids/buffers/empty52.buffer")) 
go.property("buffer53", resource.buffer("/game_objects/asteroids/buffers/empty53.buffer")) 
go.property("buffer54", resource.buffer("/game_objects/asteroids/buffers/empty54.buffer")) 
go.property("buffer55", resource.buffer("/game_objects/asteroids/buffers/empty55.buffer")) 
go.property("buffer56", resource.buffer("/game_objects/asteroids/buffers/empty56.buffer")) 
go.property("buffer57", resource.buffer("/game_objects/asteroids/buffers/empty57.buffer")) 
go.property("buffer58", resource.buffer("/game_objects/asteroids/buffers/empty58.buffer")) 
go.property("buffer59", resource.buffer("/game_objects/asteroids/buffers/empty59.buffer")) 
go.property("buffer60", resource.buffer("/game_objects/asteroids/buffers/empty60.buffer")) 
go.property("buffer61", resource.buffer("/game_objects/asteroids/buffers/empty61.buffer")) 
go.property("buffer62", resource.buffer("/game_objects/asteroids/buffers/empty62.buffer")) 
go.property("buffer63", resource.buffer("/game_objects/asteroids/buffers/empty63.buffer")) 
go.property("buffer64", resource.buffer("/game_objects/asteroids/buffers/empty64.buffer")) 
go.property("buffer65", resource.buffer("/game_objects/asteroids/buffers/empty65.buffer")) 
go.property("buffer66", resource.buffer("/game_objects/asteroids/buffers/empty66.buffer")) 
go.property("buffer67", resource.buffer("/game_objects/asteroids/buffers/empty67.buffer")) 
go.property("buffer68", resource.buffer("/game_objects/asteroids/buffers/empty68.buffer")) 
go.property("buffer69", resource.buffer("/game_objects/asteroids/buffers/empty69.buffer")) 
go.property("buffer70", resource.buffer("/game_objects/asteroids/buffers/empty70.buffer")) 
go.property("buffer71", resource.buffer("/game_objects/asteroids/buffers/empty71.buffer")) 
go.property("buffer72", resource.buffer("/game_objects/asteroids/buffers/empty72.buffer")) 
go.property("buffer73", resource.buffer("/game_objects/asteroids/buffers/empty73.buffer")) 
go.property("buffer74", resource.buffer("/game_objects/asteroids/buffers/empty74.buffer")) 
go.property("buffer75", resource.buffer("/game_objects/asteroids/buffers/empty75.buffer")) 
go.property("buffer76", resource.buffer("/game_objects/asteroids/buffers/empty76.buffer")) 
go.property("buffer77", resource.buffer("/game_objects/asteroids/buffers/empty77.buffer")) 
go.property("buffer78", resource.buffer("/game_objects/asteroids/buffers/empty78.buffer")) 
go.property("buffer79", resource.buffer("/game_objects/asteroids/buffers/empty79.buffer")) 
go.property("buffer80", resource.buffer("/game_objects/asteroids/buffers/empty80.buffer")) 
go.property("buffer81", resource.buffer("/game_objects/asteroids/buffers/empty81.buffer")) 
go.property("buffer82", resource.buffer("/game_objects/asteroids/buffers/empty82.buffer")) 
go.property("buffer83", resource.buffer("/game_objects/asteroids/buffers/empty83.buffer")) 
go.property("buffer84", resource.buffer("/game_objects/asteroids/buffers/empty84.buffer")) 
go.property("buffer85", resource.buffer("/game_objects/asteroids/buffers/empty85.buffer")) 
go.property("buffer86", resource.buffer("/game_objects/asteroids/buffers/empty86.buffer")) 
go.property("buffer87", resource.buffer("/game_objects/asteroids/buffers/empty87.buffer")) 
go.property("buffer88", resource.buffer("/game_objects/asteroids/buffers/empty88.buffer")) 
go.property("buffer89", resource.buffer("/game_objects/asteroids/buffers/empty89.buffer")) 
go.property("buffer90", resource.buffer("/game_objects/asteroids/buffers/empty90.buffer")) 
go.property("buffer91", resource.buffer("/game_objects/asteroids/buffers/empty91.buffer")) 
go.property("buffer92", resource.buffer("/game_objects/asteroids/buffers/empty92.buffer")) 
go.property("buffer93", resource.buffer("/game_objects/asteroids/buffers/empty93.buffer")) 
go.property("buffer94", resource.buffer("/game_objects/asteroids/buffers/empty94.buffer")) 
go.property("buffer95", resource.buffer("/game_objects/asteroids/buffers/empty95.buffer")) 
go.property("buffer96", resource.buffer("/game_objects/asteroids/buffers/empty96.buffer")) 
go.property("buffer97", resource.buffer("/game_objects/asteroids/buffers/empty97.buffer")) 
go.property("buffer98", resource.buffer("/game_objects/asteroids/buffers/empty98.buffer")) 
go.property("buffer99", resource.buffer("/game_objects/asteroids/buffers/empty99.buffer")) 
go.property("buffer100", resource.buffer("/game_objects/asteroids/buffers/empty100.buffer")) 

go.property("size", 3)
go.property("scale", 12)

local available_buffers = {
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
	1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1
}

local function push_vertex(self, v, index) 
	self.positions[index] = self.vertices[v].x
	self.positions[index+1] = self.vertices[v].y
	self.positions[index+2] = self.vertices[v].z
end

local function generate_vertices(self, count, distance, rand_angle_range, rand_dist_range, spikyness) 
	spikyness = spikyness or 0
	if count < 3 then
		count = 3
	end
	self.vertices = {vmath.vector4(0, 0, 10, 0)}
	local angle = math.pi * 2 / count
	for i = 2,count+1 do
		local angle_offset = (math.random() -0.5) * rand_angle_range * angle
		local distance_offset = 1 + (math.random() * 0.5) * rand_dist_range + 
		math.random() * rand_dist_range * (i%2==0 and spikyness or -spikyness)
		self.vertices[i] = vmath.vector4(
		math.cos((angle + angle_offset) * (i-2)) * distance * distance_offset, 
		math.sin((angle + angle_offset) * (i-2)) * distance * distance_offset, 
		math.random(-10, 10), 
		0)
	end
end

local function fill_buffer_data(self, vertices)
	for i = 0,#vertices-2 do
		local v2 = i+2
		local v3 = i+3
		if v3 > #vertices then 
			v3 = 2
		end
		self.positions[i*9+1] = vertices[1].x
		self.positions[i*9+2] = vertices[1].y
		self.positions[i*9+3] = vertices[1].z

		self.positions[i*9+4] = vertices[v2].x
		self.positions[i*9+5] = vertices[v2].y
		self.positions[i*9+6] = vertices[v2].z

		self.positions[i*9+7] = vertices[v3].x
		self.positions[i*9+8] = vertices[v3].y
		self.positions[i*9+9] = vertices[v3].z


		self.normals[i*9+1] = 0
		self.normals[i*9+2] = 0
		self.normals[i*9+3] = 1

		self.normals[i*9+4] = vertices[v2].x
		self.normals[i*9+5] = vertices[v2].y
		self.normals[i*9+6] = vertices[v2].z

		self.normals[i*9+7] = vertices[v3].x
		self.normals[i*9+8] = vertices[v3].y
		self.normals[i*9+9] = vertices[v3].z
	end
	resource.set_buffer(go.get("#mesh", "vertices"), self.vertex_buffer)
end

function init(self)
	for i=1,100 do
		if available_buffers[i] == 1 then
			available_buffers[i] = 0
			self.found_buffer = true
			self.buffer_index = i
			go.set("#mesh", "vertices", go.get("#asteroid_mesh_generator", "buffer" .. i))
			break
		end
	end
	if not self.found_buffer then 
		go.delete()
		return
	end
	self.vertices = {}
	self.positions = {}
	self.normals = {}
	local vertex_count = 8 + self.size
	generate_vertices(self, vertex_count, self.scale * self.size, 0.1, 1, 0.25)

	self.vertex_buffer = buffer.create(vertex_count*3, {
		{ name = hash("position"),
		type=buffer.VALUE_TYPE_FLOAT32,
		count = 3 },
		{ name = hash("normal"),
		type=buffer.VALUE_TYPE_FLOAT32,
		count = 3 }
	})

	self.positions = buffer.get_stream(self.vertex_buffer, "position")
	self.normals = buffer.get_stream(self.vertex_buffer, "normal")
	fill_buffer_data(self, self.vertices)
	go.set_position(vmath.vector3(0))
end

function final(self)
	-- Add finalization code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function update(self, dt)
	-- Add update code here
	-- Learn more: https://defold.com/manuals/script/
	-- Remove this function if not needed
end

function on_message(self, message_id, message, sender)
	-- Add message-handling code here
	-- Learn more: https://defold.com/manuals/message-passing/
	-- Remove this function if not needed
end

function on_input(self, action_id, action)
	-- Add input-handling code here. The game object this script is attached to
	-- must have acquired input focus:
	--
	--    msg.post(".", "acquire_input_focus")
	--
	-- All mapped input bindings will be received. Mouse and touch input will
	-- be received regardless of where on the screen it happened.
	-- Learn more: https://defold.com/manuals/input/
	-- Remove this function if not needed
end

function on_reload(self)
	-- Add reload-handling code here
	-- Learn more: https://defold.com/manuals/hot-reload/
	-- Remove this function if not needed
end
